from TTS.api import TTS
import sys


class TextToSpeech:
    def __init__(self,word):
        self.word = word
        self.clean_text()
    
    def clean_text(self):
        ## clean any special char that was generated by LLM (like * ** ** ///)
        self.word = self.word.replace("*","").replace("**","").replace("***","").replace("-","").replace(".","")
        
    
    
    def text_to_speech(self):
        tts = TTS(model_name="tts_models/en/ljspeech/glow-tts", progress_bar=False).to("cpu")
        tts.tts_to_file(text=self.word, file_path="output.wav")
        return "output.wav"

    


if __name__ == "__main__":
    text =TextToSpeech(sys.argv[1])
    text.text_to_speech()